### ISSUE TITLE
How to use it on macOS

### ISSUE THREAD

**Issue by draco1544** [gyroflow/mp4-merge#3]
Hi ! How I can use the app on MacOS ?

**Comment by AdrianEddy** [comment]
download the binary for macOS from the [releases ](https://github.com/gyroflow/mp4-merge/releases) page, if you have Intel mac, then `mp4_merge-mac64` file, and if you have M1/M2/M3 then `mp4_merge-mac-arm64` and then run it through Terminal as shown in the README
